config/routes.rb
FreshList::Application.routes.draw do


  devise_for :accounts
  get 'dashboard' => 'dashboard#index', :as => 'dashboard'

  root :to => "static#index"

  get ':action' => 'static#:action'

end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/models/billing_profile.rb
class BillingProfile < ActiveRecord::Base
  belongs_to :profile
end

app/models/buyer.rb
class Buyer < Profile
  has_one :cart
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :buyer
  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart

  has_one :billing_profile, :as => :buyer_billing_profile
  has_one :billing_profile, :as => :seller_billing_profile

  has_one :shipping_profile, :as => :buyer_shipping_profile
  has_one :shipping_profile, :as => :seller_shipping_profile
end

app/models/product.rb
class Product < ActiveRecord::Base  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :account

  set_inheritance_column :profile_type

  has_many :shipping_profiles
  has_many :billing_profiles
end

app/models/seller.rb
class Seller < ActiveRecord::Base
end

app/models/shipping_profile.rb
class ShippingProfile < ActiveRecord::Base
  belongs_to :profile
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_filter :authenticate_account!
  
  def index
    
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_filter :logged_in?
  layout 'static'

  def index
    render :layout => 'landing'
  end

  def logged_in?
    if current_account
      redirect_to dashboard_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breadcrumb_helper.rb
module BreadcrumbHelper
  def breadcrumbs
    @breadcrumb ||= [ { :title => 'Dashboard', :url => root_url } ]
  end

  def breadcrumb_add(title, url)
    breadcrumbs << { :title => title, :url => url }
  end

  def render_breadcrumb
    render :partial => 'layout/breadcrumb', :locals => { :breadcrumbs => breadcrumbs }
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)
    
    html = <<-HTML
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h5>#{sentence}</h5>
        <ul>#{messages}</ul>
      </div>
    HTML
    
    html.html_safe
  end
end

app/views/dashboard/index.html.haml
%h1 Dashboard

app/views/layouts/_breadcrumb.html.haml
%ul.breadcrumb
  - breadcrumbs.each do |breadcrumb|
    %li
      = link_to breadcrumb[:title], breadcrumb[:url], :title => breadcrumb[:title]
      %span.divider /
  %li.active
    = yield :title

app/views/layouts/_flashes.html.haml
- if notice || alert
  - if notice
    .alert.alert-info
      %button{:type => "button", :class => "close", :'data-dismiss' => "alert"} &times;
      = notice
  - if alert
    .alert.alert-block
      %button{:type => "button", :class => "close", :'data-dismiss' => "alert"} &times;
      = alert
  
  -# We have to wait for Rails4 to use these
  
  -# - if error
  -#   .alert.alert-error
  -#     %button{:type => "button", :class => "close", :'data-dismiss' => "alert"} &times;
  -#     = error
  -# - if success
  -#   .alert.alert-success
  -#     %button{:type => "button", :class => "close", :'data-dismiss' => "alert"} &times;
  -#     = success

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %title Boilerplate
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    
%body

  .container
    %header
      %nav.navbar.navbar-default
        %div
          .navbar-header
            = link_to "FreshList", root_url, :title => "Dashboard", :class => "navbar-brand"
          .navbar-collapse
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                = link_to "#", :title => "Account", :class => "dropdown-toggle", :'data-toggle' => "dropdown" do
                  Account
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Sign Out", destroy_account_session_path, :title => "Sign Out", :method => 'delete'
    
      = render :partial => 'layouts/flashes'
    
    = render :partial => 'layouts/breadcrumb'

    = yield
    
    %footer
      
      = link_to "about", "/about", :title => "about"

app/views/layouts/landing.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %title Boilerplate
    
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    
    = stylesheet_link_tag    "landing", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    
    /[if lt IE 9]
      = javascript_include_tag "html5shiv"
    
%body

  .navbar-wrapper

    .container
      .navbar.navbar-inverse
        .navbar-inner

          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Boilerplate

          .nav-collapse.collapse
            %ul.nav
              %li.active
                %a{:href => "#"} Home
              %li
                = link_to "About", "/about", :title => "About"
              %li
                %a{:href => "#contact"} Contact

              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Dropdown
                  %b.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"} Action
                  %li
                    %a{:href => "#"} Another action
                  %li
                    %a{:href => "#"} Something else here
                  %li.divider
                  %li.nav-header Nav header
                  %li
                    %a{:href => "#"} Separated link
                  %li
                    %a{:href => "#"} One more separated link
          
          .nav-collapse.collapse.pull-right
            %ul.nav
              %li
                = link_to "Sign In", new_account_session_path, :title => "Sign In"

  = yield

  :javascript
    !function ($) {
      $(function(){
        $('#the-carousel').carousel();
      })
    }(window.jQuery)

app/views/layouts/static.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %title Boilerplate
    = stylesheet_link_tag    "static", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    
%body
  .container
    
    #main
      = render :partial => 'layouts/flashes'
    
      = yield
    

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)

- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)

- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
  